import { JetBrains, JetBrains_Mono } from 'next/font/google'
import './globals.css'


//importing components
import Header from '@/components/Header';

const jetbrainsMono = JetBrains_Mono({ 
    subsets: ["latin"], 
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
    title: "Create next app",
    description: "Generated by create next app",
    variable: '--font-jetbrainsMono'
};

export default function RootLayout({children}) { 
    return (
        <html lang="en">
            <body className={jetbrainsMono.variable}>{children}</body>
                <Header />
                {children}<body/>
        </html>
    );
}
